services:
  votifier:
    build: .
    container_name: minecraft-votifier
    restart: unless-stopped
    ports:
      - "8192:8192"
    env_file:
      - .env
    volumes:
      - ./keys:/app/keys
      # Mount data to Minecraft server for KubeJS access
      - /var/lib/pterodactyl/volumes/284c8202-2eb5-4ba2-b7b9-519145422945/kubejs/server_data/votifier:/app/data
    networks:
      - pterodactyl_nw

networks:
  pterodactyl_nw:
    external: true
